// Tool page heading & subtitle translations for all 20 languages
// Keys: page.{toolId}.h1a, page.{toolId}.h1b (highlighted word), page.{toolId}.sub

import type { Lang } from './translations';

type ToolTranslations = Record<string, Partial<Record<Lang, string>> & { en: string }>;

export const toolTranslations: ToolTranslations = {
  // ── Merge ──
  'page.merge.h1a': { en: 'Combine PDFs in', ar: 'ادمج ملفات PDF في', ur: 'PDF فائلیں ملائیں', hi: 'PDF फ़ाइलें जोड़ें', es: 'Combina PDFs en', fr: 'Combinez des PDF en', de: 'PDFs kombinieren in', zh: '合并PDF只需', ja: 'PDFを結合', ko: 'PDF 결합', tr: 'PDF birleştir', ru: 'Объедините PDF за', it: 'Unisci PDF in', nl: 'PDF samenvoegen in', id: 'Gabung PDF dalam', th: 'รวม PDF ใน', vi: 'Gộp PDF trong', bn: 'PDF একত্র করুন', sw: 'Unganisha PDF kwa' },
  'page.merge.h1b': { en: 'seconds', ar: 'ثوانٍ', ur: 'سیکنڈز میں', hi: 'सेकंडों में', es: 'segundos', fr: 'secondes', de: 'Sekunden', zh: '几秒', ja: '数秒で', ko: '초 만에', tr: 'saniyeler', ru: 'секунды', it: 'secondi', nl: 'seconden', id: 'detik', th: 'วินาที', vi: 'giây', bn: 'সেকেন্ডে', sw: 'sekunde' },
  'page.merge.sub': { en: 'Drag, drop, reorder and merge multiple PDF files — entirely in your browser.', ar: 'اسحب وأفلت وأعد الترتيب وادمج ملفات PDF — بالكامل في متصفحك.', ur: 'PDF فائلیں کھینچیں، چھوڑیں اور ملائیں — مکمل طور پر آپ کے براؤزر میں۔', hi: 'PDF फ़ाइलें खींचें, छोड़ें और मर्ज करें — पूरी तरह आपके ब्राउज़र में।', es: 'Arrastra, reordena y combina archivos PDF — todo en tu navegador.', fr: 'Glissez, déposez et fusionnez vos PDF — entièrement dans votre navigateur.', de: 'Ziehen, ablegen und zusammenführen — komplett in Ihrem Browser.', zh: '拖放、重排并合并多个PDF文件 — 完全在浏览器中完成。', ja: 'ドラッグ＆ドロップでPDFを並べ替え、結合 — すべてブラウザ内で。', ko: '여러 PDF 파일을 드래그, 정렬, 병합 — 브라우저에서 처리.', tr: 'Sürükle, bırak ve birleştir — tamamen tarayıcınızda.', ru: 'Перетаскивайте и объединяйте PDF — прямо в браузере.', it: 'Trascina, riordina e unisci i PDF — tutto nel tuo browser.', nl: 'Sleep, sorteer en voeg PDF\'s samen — in je browser.', id: 'Seret, susun ulang dan gabungkan file PDF — sepenuhnya di browser.', th: 'ลาก วาง จัดเรียง และรวม PDF — ในเบราว์เซอร์', vi: 'Kéo, thả, sắp xếp và gộp PDF — hoàn toàn trong trình duyệt.', bn: 'টেনে এনে PDF ফাইল মার্জ করুন — সম্পূর্ণ ব্রাউজারে।', sw: 'Buruta, panga na unganisha PDF — kwenye kivinjari chako.' },
  // ── Split ──
  'page.split.h1a': { en: 'Split PDF into', ar: 'قسّم PDF إلى', ur: 'PDF تقسیم کریں', hi: 'PDF विभाजित करें', es: 'Divide PDF en', fr: 'Diviser le PDF en', de: 'PDF aufteilen in', zh: '拆分PDF为', ja: 'PDFを分割', ko: 'PDF 분할', tr: 'PDF böl', ru: 'Разделите PDF на', it: 'Dividi PDF in', nl: 'PDF splitsen in', id: 'Pisahkan PDF menjadi', th: 'แยก PDF เป็น', vi: 'Tách PDF thành', bn: 'PDF ভাগ করুন', sw: 'Gawanya PDF' },
  'page.split.h1b': { en: 'pages', ar: 'صفحات', ur: 'صفحات', hi: 'पेज', es: 'páginas', fr: 'pages', de: 'Seiten', zh: '页面', ja: 'ページに', ko: '페이지로', tr: 'sayfalara', ru: 'страницы', it: 'pagine', nl: 'pagina\'s', id: 'halaman', th: 'หน้า', vi: 'trang', bn: 'পৃষ্ঠায়', sw: 'kurasa' },
  'page.split.sub': { en: 'Extract every page from your PDF as a separate file — entirely in your browser.', ar: 'استخرج كل صفحة من PDF كملف منفصل — في متصفحك.', ur: 'ہر صفحہ الگ فائل کے طور پر نکالیں — آپ کے براؤزر میں۔', hi: 'हर पेज अलग फ़ाइल के रूप में निकालें — ब्राउज़र में।', es: 'Extrae cada página como archivo separado — en tu navegador.', fr: 'Extrayez chaque page en fichier séparé — dans votre navigateur.', de: 'Jede Seite als separate Datei extrahieren — in Ihrem Browser.', zh: '将PDF的每一页提取为单独文件 — 在浏览器中完成。', ja: '各ページを個別ファイルとして抽出 — ブラウザ内で。', ko: '각 페이지를 개별 파일로 추출 — 브라우저에서.', tr: 'Her sayfayı ayrı dosya olarak çıkarın — tarayıcınızda.', ru: 'Извлеките каждую страницу как отдельный файл — в браузере.', it: 'Estrai ogni pagina come file separato — nel tuo browser.', nl: 'Elke pagina als apart bestand — in je browser.', id: 'Ekstrak setiap halaman sebagai file terpisah — di browser.', th: 'แยกทุกหน้าเป็นไฟล์แยก — ในเบราว์เซอร์', vi: 'Trích xuất từng trang thành file riêng — trong trình duyệt.', bn: 'প্রতিটি পৃষ্ঠা আলাদা ফাইল হিসেবে বের করুন — ব্রাউজারে।', sw: 'Toa kila ukurasa kama faili tofauti — kwenye kivinjari.' },
  // ── Compress ──
  'page.compress.h1a': { en: 'Compress PDF', ar: 'ضغط ملفات', ur: 'PDF کمپریس کریں', hi: 'PDF कंप्रेस करें', es: 'Comprimir archivos', fr: 'Compresser des', de: 'PDF komprimieren', zh: '压缩PDF', ja: 'PDFを圧縮', ko: 'PDF 압축', tr: 'PDF sıkıştır', ru: 'Сжать PDF', it: 'Comprimi PDF', nl: 'PDF comprimeren', id: 'Kompres PDF', th: 'บีบอัด PDF', vi: 'Nén PDF', bn: 'PDF কম্প্রেস করুন', sw: 'Bana PDF' },
  'page.compress.h1b': { en: 'files', ar: 'PDF', ur: 'فائلیں', hi: 'फ़ाइलें', es: 'PDF', fr: 'PDF', de: 'Dateien', zh: '文件', ja: 'ファイル', ko: '파일', tr: 'dosyaları', ru: 'файлы', it: 'file', nl: 'bestanden', id: 'file', th: 'ไฟล์', vi: 'tệp', bn: 'ফাইল', sw: 'faili' },
  'page.compress.sub': { en: 'Reduce file size by stripping metadata — entirely in your browser.', ar: 'قلل حجم الملف بإزالة البيانات الوصفية — في متصفحك.', ur: 'میٹا ڈیٹا ہٹا کر فائل سائز کم کریں — آپ کے براؤزر میں۔', hi: 'मेटाडेटा हटाकर फ़ाइल का आकार कम करें — ब्राउज़र में।', es: 'Reduce el tamaño eliminando metadatos — en tu navegador.', fr: 'Réduisez la taille en supprimant les métadonnées — dans votre navigateur.', de: 'Dateigröße durch Entfernen von Metadaten reduzieren — in Ihrem Browser.', zh: '通过去除元数据减小文件大小 — 在浏览器中完成。', ja: 'メタデータを削除してファイルサイズを縮小 — ブラウザ内で。', ko: '메타데이터를 제거하여 파일 크기 축소 — 브라우저에서.', tr: 'Meta verileri kaldırarak dosya boyutunu küçültün — tarayıcınızda.', ru: 'Уменьшите размер, удалив метаданные — в браузере.', it: 'Riduci le dimensioni rimuovendo i metadati — nel tuo browser.', nl: 'Verklein bestanden door metadata te verwijderen — in je browser.', id: 'Kurangi ukuran file dengan menghapus metadata — di browser.', th: 'ลดขนาดไฟล์โดยลบ metadata — ในเบราว์เซอร์', vi: 'Giảm kích thước bằng cách loại bỏ metadata — trong trình duyệt.', bn: 'মেটাডেটা সরিয়ে ফাইলের আকার কমান — ব্রাউজারে।', sw: 'Punguza ukubwa kwa kuondoa metadata — kwenye kivinjari.' },
  // ── Rotate ──
  'page.rotate.h1a': { en: 'Rotate PDF', ar: 'تدوير صفحات', ur: 'PDF گھمائیں', hi: 'PDF घुमाएं', es: 'Rotar páginas', fr: 'Rotation des', de: 'PDF-Seiten', zh: '旋转PDF', ja: 'PDFを回転', ko: 'PDF 회전', tr: 'PDF döndür', ru: 'Повернуть PDF', it: 'Ruota le', nl: 'PDF roteren', id: 'Putar PDF', th: 'หมุน PDF', vi: 'Xoay PDF', bn: 'PDF ঘোরান', sw: 'Zungusha PDF' },
  'page.rotate.h1b': { en: 'pages', ar: 'PDF', ur: 'صفحات', hi: 'पेज', es: 'PDF', fr: 'pages PDF', de: 'drehen', zh: '页面', ja: 'ページ', ko: '페이지', tr: 'sayfaları', ru: 'страницы', it: 'pagine PDF', nl: 'pagina\'s', id: 'halaman', th: 'หน้า', vi: 'trang', bn: 'পৃষ্ঠা', sw: 'kurasa' },
  'page.rotate.sub': { en: 'Rotate all pages by 90°, 180°, or 270° — entirely in your browser.', ar: 'قم بتدوير جميع الصفحات 90° أو 180° أو 270° — في متصفحك.', ur: 'تمام صفحات 90°، 180° یا 270° گھمائیں — آپ کے براؤزر میں۔', hi: 'सभी पेज 90°, 180° या 270° घुमाएं — ब्राउज़र में।', es: 'Rota todas las páginas 90°, 180° o 270° — en tu navegador.', fr: 'Tournez toutes les pages de 90°, 180° ou 270° — dans votre navigateur.', de: 'Alle Seiten um 90°, 180° oder 270° drehen — in Ihrem Browser.', zh: '将所有页面旋转90°、180°或270° — 在浏览器中完成。', ja: 'すべてのページを90°、180°、270°回転 — ブラウザ内で。', ko: '모든 페이지를 90°, 180°, 270° 회전 — 브라우저에서.', tr: 'Tüm sayfaları 90°, 180° veya 270° döndürün — tarayıcınızda.', ru: 'Поверните все страницы на 90°, 180° или 270° — в браузере.', it: 'Ruota tutte le pagine di 90°, 180° o 270° — nel tuo browser.', nl: 'Roteer alle pagina\'s 90°, 180° of 270° — in je browser.', id: 'Putar semua halaman 90°, 180° atau 270° — di browser.', th: 'หมุนทุกหน้า 90°, 180° หรือ 270° — ในเบราว์เซอร์', vi: 'Xoay tất cả trang 90°, 180° hoặc 270° — trong trình duyệt.', bn: 'সব পৃষ্ঠা 90°, 180° বা 270° ঘোরান — ব্রাউজারে।', sw: 'Zungusha kurasa zote 90°, 180° au 270° — kwenye kivinjari.' },
  // ── Convert ──
  'page.convert.h1a': { en: 'Convert', ar: 'حوّل', ur: 'تبدیل کریں', hi: 'कन्वर्ट करें', es: 'Convierte', fr: 'Convertir des', de: 'Dateien', zh: '转换', ja: 'ファイルを', ko: '파일', tr: 'Dosyaları', ru: 'Конвертируйте', it: 'Converti', nl: 'Bestanden', id: 'Konversi', th: 'แปลง', vi: 'Chuyển đổi', bn: 'রূপান্তর করুন', sw: 'Badilisha' },
  'page.convert.h1b': { en: 'files easily', ar: 'الملفات بسهولة', ur: 'فائلیں آسانی سے', hi: 'फ़ाइलें आसानी से', es: 'archivos fácilmente', fr: 'fichiers facilement', de: 'einfach konvertieren', zh: '文件轻松', ja: '簡単変換', ko: '쉽게 변환', tr: 'kolayca dönüştür', ru: 'файлы легко', it: 'file facilmente', nl: 'eenvoudig converteren', id: 'file dengan mudah', th: 'ไฟล์ง่ายๆ', vi: 'tệp dễ dàng', bn: 'ফাইল সহজে', sw: 'faili kwa urahisi' },
  'page.convert.sub': { en: 'Images to PDF, PDF to images, image formats, and XML — all in your browser.', ar: 'صور إلى PDF، PDF إلى صور، صيغ الصور، وXML — كل شيء في متصفحك.', ur: 'تصاویر سے PDF، PDF سے تصاویر — سب آپ کے براؤزر میں۔', hi: 'इमेज से PDF, PDF से इमेज — सब ब्राउज़र में।', es: 'Imágenes a PDF, PDF a imágenes y más — todo en tu navegador.', fr: 'Images en PDF, PDF en images — tout dans votre navigateur.', de: 'Bilder zu PDF, PDF zu Bildern — alles in Ihrem Browser.', zh: '图片转PDF、PDF转图片 — 全在浏览器中。', ja: '画像→PDF、PDF→画像 — すべてブラウザ内で。', ko: '이미지→PDF, PDF→이미지 — 브라우저에서.', tr: 'Resimlerden PDF, PDF\'den resimlere — tarayıcınızda.', ru: 'Изображения в PDF, PDF в изображения — в браузере.', it: 'Immagini in PDF, PDF in immagini — nel tuo browser.', nl: 'Afbeeldingen naar PDF, PDF naar afbeeldingen — in je browser.', id: 'Gambar ke PDF, PDF ke gambar — di browser.', th: 'รูปเป็น PDF, PDF เป็นรูป — ในเบราว์เซอร์', vi: 'Ảnh sang PDF, PDF sang ảnh — trong trình duyệt.', bn: 'ছবি থেকে PDF, PDF থেকে ছবি — ব্রাউজারে।', sw: 'Picha hadi PDF, PDF hadi picha — kwenye kivinjari.' },
  // ── Encrypt ──
  'page.encrypt.h1a': { en: 'Encrypt', ar: 'تشفير', ur: 'انکرپٹ کریں', hi: 'एन्क्रिप्ट करें', es: 'Cifrar', fr: 'Chiffrer les', de: 'PDFs', zh: '加密', ja: 'PDFを暗号化', ko: 'PDF 암호화', tr: 'PDF şifrele', ru: 'Зашифровать', it: 'Crittografa', nl: 'PDF versleutelen', id: 'Enkripsi', th: 'เข้ารหัส', vi: 'Mã hóa', bn: 'এনক্রিপ্ট করুন', sw: 'Simba' },
  'page.encrypt.h1b': { en: 'PDFs', ar: 'PDF', ur: 'PDF', hi: 'PDF', es: 'PDF', fr: 'PDF', de: 'verschlüsseln', zh: 'PDF', ja: '', ko: '', tr: '', ru: 'PDF', it: 'PDF', nl: '', id: 'PDF', th: 'PDF', vi: 'PDF', bn: 'PDF', sw: 'PDF' },
  'page.encrypt.sub': { en: 'Add password protection to your PDF files — processed locally in your browser.', ar: 'أضف حماية بكلمة مرور لملفات PDF — في متصفحك.', ur: 'اپنی PDF فائلوں میں پاس ورڈ شامل کریں — آپ کے براؤزر میں۔', hi: 'PDF फ़ाइलों में पासवर्ड सुरक्षा जोड़ें — ब्राउज़र में।', es: 'Añade protección con contraseña — en tu navegador.', fr: 'Protégez vos PDF par mot de passe — dans votre navigateur.', de: 'Passwortschutz hinzufügen — in Ihrem Browser.', zh: '为PDF文件添加密码保护 — 在浏览器中完成。', ja: 'PDFにパスワード保護を追加 — ブラウザ内で。', ko: 'PDF에 비밀번호 보호 추가 — 브라우저에서.', tr: 'PDF dosyalarınıza parola koruması ekleyin — tarayıcınızda.', ru: 'Добавьте защиту паролем — в браузере.', it: 'Aggiungi protezione con password — nel tuo browser.', nl: 'Wachtwoordbeveiliging toevoegen — in je browser.', id: 'Tambahkan perlindungan kata sandi — di browser.', th: 'เพิ่มรหัสผ่านป้องกัน PDF — ในเบราว์เซอร์', vi: 'Thêm bảo vệ mật khẩu cho PDF — trong trình duyệt.', bn: 'PDF ফাইলে পাসওয়ার্ড সুরক্ষা যোগ করুন — ব্রাউজারে।', sw: 'Ongeza ulinzi wa nenosiri — kwenye kivinjari.' },
  // ── PDF to Word ──
  'page.pdfToWord.h1a': { en: 'PDF to', ar: 'PDF إلى', ur: 'PDF سے', hi: 'PDF से', es: 'PDF a', fr: 'PDF en', de: 'PDF zu', zh: 'PDF转', ja: 'PDFから', ko: 'PDF를', tr: 'PDF\'den', ru: 'PDF в', it: 'PDF in', nl: 'PDF naar', id: 'PDF ke', th: 'PDF เป็น', vi: 'PDF sang', bn: 'PDF থেকে', sw: 'PDF hadi' },
  'page.pdfToWord.h1b': { en: 'Word', ar: 'Word', ur: 'Word', hi: 'Word', es: 'Word', fr: 'Word', de: 'Word', zh: 'Word', ja: 'Word', ko: 'Word로', tr: 'Word', ru: 'Word', it: 'Word', nl: 'Word', id: 'Word', th: 'Word', vi: 'Word', bn: 'Word', sw: 'Word' },
  'page.pdfToWord.sub': { en: 'Convert your PDF documents to editable Word files.', ar: 'حوّل مستندات PDF إلى ملفات Word قابلة للتحرير.', ur: 'PDF دستاویزات کو ورڈ فائلوں میں تبدیل کریں۔', hi: 'PDF दस्तावेज़ों को Word फ़ाइलों में बदलें।', es: 'Convierte documentos PDF a archivos Word editables.', fr: 'Convertissez vos PDF en fichiers Word éditables.', de: 'PDF-Dokumente in bearbeitbare Word-Dateien konvertieren.', zh: '将PDF文档转换为可编辑的Word文件。', ja: 'PDF文書を編集可能なWordファイルに変換。', ko: 'PDF 문서를 편집 가능한 Word 파일로 변환.', tr: 'PDF belgelerini düzenlenebilir Word dosyalarına dönüştürün.', ru: 'Конвертируйте PDF в редактируемые файлы Word.', it: 'Converti documenti PDF in file Word modificabili.', nl: 'Converteer PDF naar bewerkbare Word-bestanden.', id: 'Konversi dokumen PDF ke file Word yang dapat diedit.', th: 'แปลงเอกสาร PDF เป็นไฟล์ Word ที่แก้ไขได้', vi: 'Chuyển đổi tài liệu PDF sang file Word có thể chỉnh sửa.', bn: 'PDF ডকুমেন্ট সম্পাদনযোগ্য Word ফাইলে রূপান্তর করুন।', sw: 'Badilisha hati za PDF kuwa faili za Word.' },
  // ── Word to PDF ──
  'page.wordToPdf.h1a': { en: 'Word to', ar: 'Word إلى', ur: 'Word سے', hi: 'Word से', es: 'Word a', fr: 'Word en', de: 'Word zu', zh: 'Word转', ja: 'Wordから', ko: 'Word를', tr: 'Word\'den', ru: 'Word в', it: 'Word in', nl: 'Word naar', id: 'Word ke', th: 'Word เป็น', vi: 'Word sang', bn: 'Word থেকে', sw: 'Word hadi' },
  'page.wordToPdf.h1b': { en: 'PDF', ar: 'PDF', ur: 'PDF', hi: 'PDF', es: 'PDF', fr: 'PDF', de: 'PDF', zh: 'PDF', ja: 'PDF', ko: 'PDF로', tr: 'PDF', ru: 'PDF', it: 'PDF', nl: 'PDF', id: 'PDF', th: 'PDF', vi: 'PDF', bn: 'PDF', sw: 'PDF' },
  'page.wordToPdf.sub': { en: 'Convert Word documents to PDF format instantly.', ar: 'حوّل مستندات Word إلى PDF فوراً.', ur: 'Word دستاویزات کو فوری PDF میں تبدیل کریں۔', hi: 'Word दस्तावेज़ तुरंत PDF में बदलें।', es: 'Convierte documentos Word a PDF al instante.', fr: 'Convertissez des documents Word en PDF instantanément.', de: 'Word-Dokumente sofort in PDF konvertieren.', zh: '将Word文档即时转换为PDF格式。', ja: 'Word文書をPDFに即座に変換。', ko: 'Word 문서를 즉시 PDF로 변환.', tr: 'Word belgelerini anında PDF\'ye dönüştürün.', ru: 'Мгновенно конвертируйте Word в PDF.', it: 'Converti documenti Word in PDF istantaneamente.', nl: 'Converteer Word-documenten direct naar PDF.', id: 'Konversi dokumen Word ke PDF secara instan.', th: 'แปลงเอกสาร Word เป็น PDF ทันที', vi: 'Chuyển đổi tài liệu Word sang PDF ngay lập tức.', bn: 'Word ডকুমেন্ট তাৎক্ষণিক PDF এ রূপান্তর করুন।', sw: 'Badilisha hati za Word kuwa PDF papo hapo.' },
  // ── Image to PDF ──
  'page.imageToPdf.h1': { en: 'Image to PDF', ar: 'صورة إلى PDF', ur: 'تصویر سے PDF', hi: 'इमेज से PDF', es: 'Imagen a PDF', fr: 'Image en PDF', de: 'Bild zu PDF', zh: '图片转PDF', ja: '画像からPDF', ko: '이미지를 PDF로', tr: 'Resim PDF\'ye', ru: 'Изображение в PDF', it: 'Immagine in PDF', nl: 'Afbeelding naar PDF', id: 'Gambar ke PDF', th: 'รูปเป็น PDF', vi: 'Ảnh sang PDF', bn: 'ছবি থেকে PDF', sw: 'Picha hadi PDF' },
  'page.imageToPdf.sub': { en: 'Convert and combine JPG, PNG, or WEBP images into a single PDF. Drag to reorder.', ar: 'حوّل وادمج صور JPG أو PNG أو WEBP في ملف PDF واحد. اسحب لإعادة الترتيب.', ur: 'JPG, PNG یا WEBP تصاویر کو ایک PDF میں تبدیل اور ملائیں۔', hi: 'JPG, PNG या WEBP इमेज को एक PDF में बदलें और जोड़ें।', es: 'Convierte y combina imágenes JPG, PNG o WEBP en un solo PDF.', fr: 'Convertissez et combinez des images en un seul PDF.', de: 'Bilder in ein einzelnes PDF konvertieren und kombinieren.', zh: '将JPG、PNG或WEBP图片合并转换为一个PDF。', ja: 'JPG、PNG、WEBP画像を1つのPDFに変換・結合。', ko: 'JPG, PNG, WEBP 이미지를 하나의 PDF로 변환 및 결합.', tr: 'JPG, PNG veya WEBP resimlerini tek PDF\'de birleştirin.', ru: 'Конвертируйте и объедините изображения в один PDF.', it: 'Converti e combina immagini in un unico PDF.', nl: 'Converteer en combineer afbeeldingen tot één PDF.', id: 'Konversi dan gabungkan gambar menjadi satu PDF.', th: 'แปลงและรวมรูปภาพเป็น PDF เดียว', vi: 'Chuyển đổi và gộp ảnh thành một PDF duy nhất.', bn: 'ছবিগুলো একত্র করে একটি PDF তৈরি করুন।', sw: 'Badilisha na unganisha picha kuwa PDF moja.' },
  // ── Delete Pages ──
  'page.deletePages.h1a': { en: 'Delete PDF', ar: 'حذف صفحات', ur: 'PDF صفحات حذف کریں', hi: 'PDF पेज हटाएं', es: 'Eliminar páginas', fr: 'Supprimer des pages', de: 'PDF-Seiten', zh: '删除PDF', ja: 'PDFページを', ko: 'PDF 페이지', tr: 'PDF sayfalarını', ru: 'Удалить страницы', it: 'Elimina pagine', nl: 'PDF-pagina\'s', id: 'Hapus halaman', th: 'ลบหน้า', vi: 'Xóa trang', bn: 'PDF পৃষ্ঠা মুছুন', sw: 'Futa kurasa' },
  'page.deletePages.h1b': { en: 'Pages', ar: 'PDF', ur: '', hi: '', es: 'PDF', fr: 'PDF', de: 'löschen', zh: '页面', ja: '削除', ko: '삭제', tr: 'sil', ru: 'PDF', it: 'PDF', nl: 'verwijderen', id: 'PDF', th: 'PDF', vi: 'PDF', bn: '', sw: 'za PDF' },
  'page.deletePages.sub': { en: 'Remove unwanted pages from your PDF — entirely in your browser.', ar: 'أزل الصفحات غير المرغوبة من PDF — في متصفحك.', ur: 'ناپسندیدہ صفحات ہٹائیں — آپ کے براؤزر میں۔', hi: 'अनचाहे पेज हटाएं — ब्राउज़र में।', es: 'Elimina páginas no deseadas — en tu navegador.', fr: 'Supprimez les pages indésirables — dans votre navigateur.', de: 'Unerwünschte Seiten entfernen — in Ihrem Browser.', zh: '删除PDF中不需要的页面 — 在浏览器中完成。', ja: '不要なページを削除 — ブラウザ内で。', ko: '원하지 않는 페이지 제거 — 브라우저에서.', tr: 'İstenmeyen sayfaları kaldırın — tarayıcınızda.', ru: 'Удалите ненужные страницы — в браузере.', it: 'Rimuovi le pagine indesiderate — nel tuo browser.', nl: 'Verwijder ongewenste pagina\'s — in je browser.', id: 'Hapus halaman yang tidak diinginkan — di browser.', th: 'ลบหน้าที่ไม่ต้องการ — ในเบราว์เซอร์', vi: 'Xóa trang không cần thiết — trong trình duyệt.', bn: 'অবাঞ্ছিত পৃষ্ঠা মুছুন — ব্রাউজারে।', sw: 'Ondoa kurasa zisizohitajika — kwenye kivinjari.' },
  // ── Extract Pages ──
  'page.extractPages.h1a': { en: 'Extract PDF', ar: 'استخراج صفحات', ur: 'PDF صفحات نکالیں', hi: 'PDF पेज निकालें', es: 'Extraer páginas', fr: 'Extraire des pages', de: 'PDF-Seiten', zh: '提取PDF', ja: 'PDFページを', ko: 'PDF 페이지', tr: 'PDF sayfalarını', ru: 'Извлечь страницы', it: 'Estrai pagine', nl: 'PDF-pagina\'s', id: 'Ekstrak halaman', th: 'แยกหน้า', vi: 'Trích xuất trang', bn: 'PDF পৃষ্ঠা বের করুন', sw: 'Toa kurasa' },
  'page.extractPages.h1b': { en: 'Pages', ar: 'PDF', ur: '', hi: '', es: 'PDF', fr: 'PDF', de: 'extrahieren', zh: '页面', ja: '抽出', ko: '추출', tr: 'çıkar', ru: 'PDF', it: 'PDF', nl: 'extraheren', id: 'PDF', th: 'PDF', vi: 'PDF', bn: '', sw: 'za PDF' },
  'page.extractPages.sub': { en: 'Pull specific pages from any PDF into a new document.', ar: 'استخرج صفحات محددة من أي PDF إلى مستند جديد.', ur: 'مخصوص صفحات نئی دستاویز میں نکالیں۔', hi: 'किसी भी PDF से विशिष्ट पेज नए दस्तावेज़ में निकालें।', es: 'Extrae páginas específicas a un nuevo documento.', fr: 'Extrayez des pages spécifiques dans un nouveau document.', de: 'Bestimmte Seiten in ein neues Dokument extrahieren.', zh: '从PDF中提取特定页面到新文档。', ja: '特定のページを新しい文書に抽出。', ko: '특정 페이지를 새 문서로 추출.', tr: 'Belirli sayfaları yeni belgeye çıkarın.', ru: 'Извлеките конкретные страницы в новый документ.', it: 'Estrai pagine specifiche in un nuovo documento.', nl: 'Haal specifieke pagina\'s op in een nieuw document.', id: 'Ambil halaman tertentu ke dokumen baru.', th: 'ดึงหน้าเฉพาะจาก PDF เป็นเอกสารใหม่', vi: 'Trích xuất trang cụ thể sang tài liệu mới.', bn: 'নির্দিষ্ট পৃষ্ঠা নতুন নথিতে বের করুন।', sw: 'Toa kurasa maalum kwenye hati mpya.' },
  // ── Reorder Pages ──
  'page.reorderPages.h1': { en: 'Reorder PDF Pages', ar: 'إعادة ترتيب صفحات PDF', ur: 'PDF صفحات دوبارہ ترتیب دیں', hi: 'PDF पेज पुनर्व्यवस्थित करें', es: 'Reordenar páginas PDF', fr: 'Réorganiser les pages PDF', de: 'PDF-Seiten neu ordnen', zh: '重新排列PDF页面', ja: 'PDFページの並べ替え', ko: 'PDF 페이지 재정렬', tr: 'PDF sayfalarını yeniden sırala', ru: 'Переставить страницы PDF', it: 'Riordina le pagine PDF', nl: 'PDF-pagina\'s herschikken', id: 'Atur ulang halaman PDF', th: 'จัดเรียงหน้า PDF ใหม่', vi: 'Sắp xếp lại trang PDF', bn: 'PDF পৃষ্ঠা পুনর্বিন্যাস করুন', sw: 'Panga upya kurasa za PDF' },
  'page.reorderPages.sub': { en: 'Drag and drop to rearrange pages in your PDF document.', ar: 'اسحب وأفلت لإعادة ترتيب الصفحات في مستند PDF.', ur: 'صفحات کو دوبارہ ترتیب دینے کے لیے کھینچیں اور چھوڑیں۔', hi: 'PDF दस्तावेज़ में पेज पुनर्व्यवस्थित करने के लिए खींचें और छोड़ें।', es: 'Arrastra y suelta para reorganizar las páginas.', fr: 'Glissez-déposez pour réorganiser les pages.', de: 'Seiten per Drag & Drop neu anordnen.', zh: '拖放以重新排列PDF页面。', ja: 'ドラッグ＆ドロップでページを並べ替え。', ko: '드래그 앤 드롭으로 페이지 재정렬.', tr: 'Sayfaları sürükle bırak ile yeniden sıralayın.', ru: 'Перетаскивайте страницы для изменения порядка.', it: 'Trascina e rilascia per riordinare le pagine.', nl: 'Sleep en drop om pagina\'s te herschikken.', id: 'Seret dan lepas untuk mengatur ulang halaman.', th: 'ลากและวางเพื่อจัดเรียงหน้าใหม่', vi: 'Kéo và thả để sắp xếp lại trang.', bn: 'পৃষ্ঠা পুনর্বিন্যাস করতে টেনে ছাড়ুন।', sw: 'Buruta na udondoshe kupanga kurasa upya.' },
  // ── PDF Form Filler ──
  'page.formFiller.h1a': { en: 'Fill PDF', ar: 'ملء نماذج', ur: 'PDF فارم بھریں', hi: 'PDF फ़ॉर्म भरें', es: 'Rellenar formularios', fr: 'Remplir des formulaires', de: 'PDF-Formulare', zh: '填写PDF', ja: 'PDFフォームを', ko: 'PDF 양식', tr: 'PDF formlarını', ru: 'Заполнить формы', it: 'Compila moduli', nl: 'PDF-formulieren', id: 'Isi formulir', th: 'กรอกฟอร์ม', vi: 'Điền biểu mẫu', bn: 'PDF ফর্ম পূরণ করুন', sw: 'Jaza fomu' },
  'page.formFiller.h1b': { en: 'Forms', ar: 'PDF', ur: '', hi: '', es: 'PDF', fr: 'PDF', de: 'ausfüllen', zh: '表单', ja: '入力', ko: '채우기', tr: 'doldur', ru: 'PDF', it: 'PDF', nl: 'invullen', id: 'PDF', th: 'PDF', vi: 'PDF', bn: '', sw: 'za PDF' },
  'page.formFiller.sub': { en: 'Detect and fill form fields in any PDF — entirely in your browser.', ar: 'اكتشف واملأ حقول النماذج في أي PDF — في متصفحك.', ur: 'کسی بھی PDF میں فارم فیلڈز تلاش اور بھریں — آپ کے براؤزر میں۔', hi: 'किसी भी PDF में फ़ॉर्म फ़ील्ड खोजें और भरें — ब्राउज़र में।', es: 'Detecta y rellena campos de formulario — en tu navegador.', fr: 'Détectez et remplissez les champs — dans votre navigateur.', de: 'Formularfelder erkennen und ausfüllen — in Ihrem Browser.', zh: '检测并填写PDF中的表单字段 — 在浏览器中完成。', ja: 'フォームフィールドを検出して入力 — ブラウザ内で。', ko: '양식 필드를 감지하고 채우기 — 브라우저에서.', tr: 'Form alanlarını tespit edip doldurun — tarayıcınızda.', ru: 'Найдите и заполните поля формы — в браузере.', it: 'Rileva e compila i campi modulo — nel tuo browser.', nl: 'Detecteer en vul formuliervelden in — in je browser.', id: 'Deteksi dan isi kolom formulir — di browser.', th: 'ตรวจจับและกรอกฟิลด์ในฟอร์ม — ในเบราว์เซอร์', vi: 'Phát hiện và điền trường biểu mẫu — trong trình duyệt.', bn: 'ফর্ম ফিল্ড খুঁজুন এবং পূরণ করুন — ব্রাউজারে।', sw: 'Gundua na jaza sehemu za fomu — kwenye kivinjari.' },
  // ── Crop Pages ──
  'page.cropPages.h1': { en: 'Crop PDF Pages', ar: 'اقتصاص صفحات PDF', ur: 'PDF صفحات کراپ کریں', hi: 'PDF पेज क्रॉप करें', es: 'Recortar páginas PDF', fr: 'Rogner les pages PDF', de: 'PDF-Seiten zuschneiden', zh: '裁剪PDF页面', ja: 'PDFページのトリミング', ko: 'PDF 페이지 자르기', tr: 'PDF sayfalarını kırp', ru: 'Обрезать страницы PDF', it: 'Ritaglia pagine PDF', nl: 'PDF-pagina\'s bijsnijden', id: 'Pangkas halaman PDF', th: 'ครอปหน้า PDF', vi: 'Cắt trang PDF', bn: 'PDF পৃষ্ঠা ক্রপ করুন', sw: 'Kata kurasa za PDF' },
  'page.cropPages.sub': { en: 'Trim margins on all pages of your PDF document.', ar: 'قص الهوامش في جميع صفحات مستند PDF.', ur: 'PDF کے تمام صفحات کے حاشیے تراشیں۔', hi: 'PDF के सभी पेजों के मार्जिन ट्रिम करें।', es: 'Recorta los márgenes de todas las páginas.', fr: 'Rognez les marges de toutes les pages.', de: 'Ränder aller Seiten zuschneiden.', zh: '修剪PDF文档所有页面的边距。', ja: '全ページのマージンをトリミング。', ko: '모든 페이지의 여백 자르기.', tr: 'Tüm sayfalardaki kenar boşluklarını kırpın.', ru: 'Обрежьте поля всех страниц.', it: 'Taglia i margini di tutte le pagine.', nl: 'Snijd marges bij van alle pagina\'s.', id: 'Pangkas margin semua halaman.', th: 'ตัดขอบทุกหน้าของเอกสาร PDF', vi: 'Cắt lề tất cả các trang.', bn: 'সব পৃষ্ঠার মার্জিন ছাঁটুন।', sw: 'Kata pembezoni za kurasa zote.' },
  // ── Page Numbers ──
  'page.pageNumbers.h1a': { en: 'Add', ar: 'إضافة', ur: 'شامل کریں', hi: 'जोड़ें', es: 'Añadir', fr: 'Ajouter des', de: 'Seitenzahlen', zh: '添加', ja: 'ページ番号を', ko: '페이지 번호', tr: 'Sayfa numarası', ru: 'Добавить', it: 'Aggiungi', nl: 'Paginanummers', id: 'Tambahkan', th: 'เพิ่ม', vi: 'Thêm', bn: 'যোগ করুন', sw: 'Ongeza' },
  'page.pageNumbers.h1b': { en: 'Page Numbers', ar: 'أرقام الصفحات', ur: 'صفحہ نمبرز', hi: 'पेज नंबर', es: 'números de página', fr: 'numéros de page', de: 'hinzufügen', zh: '页码', ja: '追加', ko: '추가', tr: 'ekle', ru: 'номера страниц', it: 'numeri di pagina', nl: 'toevoegen', id: 'nomor halaman', th: 'เลขหน้า', vi: 'số trang', bn: 'পৃষ্ঠা নম্বর', sw: 'nambari za kurasa' },
  'page.pageNumbers.sub': { en: 'Number every page of your PDF — choose top or bottom position.', ar: 'رقّم كل صفحة في PDF — اختر الأعلى أو الأسفل.', ur: 'ہر صفحے کو نمبر دیں — اوپر یا نیچے منتخب کریں۔', hi: 'हर पेज को नंबर दें — ऊपर या नीचे चुनें।', es: 'Numera cada página — elige arriba o abajo.', fr: 'Numérotez chaque page — choisissez haut ou bas.', de: 'Jede Seite nummerieren — oben oder unten.', zh: '为PDF每一页编号 — 选择顶部或底部位置。', ja: '全ページに番号を追加 — 上部または下部を選択。', ko: '모든 페이지에 번호 추가 — 상단 또는 하단 선택.', tr: 'Her sayfayı numaralandırın — üst veya alt seçin.', ru: 'Пронумеруйте каждую страницу — сверху или снизу.', it: 'Numera ogni pagina — scegli sopra o sotto.', nl: 'Nummer elke pagina — kies boven of onder.', id: 'Beri nomor setiap halaman — pilih atas atau bawah.', th: 'ใส่เลขหน้าทุกหน้า — เลือกด้านบนหรือล่าง', vi: 'Đánh số mỗi trang — chọn trên hoặc dưới.', bn: 'প্রতিটি পৃষ্ঠায় নম্বর দিন — উপরে বা নিচে বেছে নিন।', sw: 'Nambari kila ukurasa — chagua juu au chini.' },
  // ── Add Watermark ──
  'page.watermark.h1a': { en: 'Add', ar: 'إضافة', ur: 'شامل کریں', hi: 'जोड़ें', es: 'Añadir', fr: 'Ajouter un', de: 'Wasserzeichen', zh: '添加', ja: '透かしを', ko: '워터마크', tr: 'Filigran', ru: 'Добавить', it: 'Aggiungi', nl: 'Watermerk', id: 'Tambahkan', th: 'เพิ่ม', vi: 'Thêm', bn: 'যোগ করুন', sw: 'Ongeza' },
  'page.watermark.h1b': { en: 'Watermark to PDF', ar: 'علامة مائية إلى PDF', ur: 'واٹر مارک PDF میں', hi: 'वॉटरमार्क PDF में', es: 'marca de agua a PDF', fr: 'filigrane au PDF', de: 'zum PDF hinzufügen', zh: '水印到PDF', ja: 'PDFに追加', ko: 'PDF에 추가', tr: 'PDF\'ye ekle', ru: 'водяной знак в PDF', it: 'filigrana al PDF', nl: 'aan PDF toevoegen', id: 'watermark ke PDF', th: 'ลายน้ำใน PDF', vi: 'watermark vào PDF', bn: 'ওয়াটারমার্ক PDF এ', sw: 'alama ya maji kwenye PDF' },
  'page.watermark.sub': { en: 'Stamp your PDFs with custom text watermarks — entirely in your browser.', ar: 'أضف علامات مائية نصية مخصصة على ملفات PDF — في متصفحك.', ur: 'اپنی PDF پر حسب ضرورت واٹر مارک لگائیں — آپ کے براؤزر میں۔', hi: 'कस्टम टेक्स्ट वॉटरमार्क लगाएं — ब्राउज़र में।', es: 'Añade marcas de agua de texto — en tu navegador.', fr: 'Ajoutez des filigranes texte — dans votre navigateur.', de: 'Wasserzeichen auf PDFs — in Ihrem Browser.', zh: '为PDF添加自定义文字水印 — 在浏览器中完成。', ja: 'カスタムテキスト透かしを追加 — ブラウザ内で。', ko: '사용자 정의 텍스트 워터마크 추가 — 브라우저에서.', tr: 'PDF\'lere özel metin filigranı ekleyin — tarayıcınızda.', ru: 'Добавьте текстовые водяные знаки — в браузере.', it: 'Aggiungi filigrane personalizzate — nel tuo browser.', nl: 'Voeg watermerken toe — in je browser.', id: 'Tambahkan watermark teks kustom — di browser.', th: 'เพิ่มลายน้ำข้อความ — ในเบราว์เซอร์', vi: 'Đóng dấu watermark văn bản — trong trình duyệt.', bn: 'কাস্টম টেক্সট ওয়াটারমার্ক যোগ করুন — ব্রাউজারে।', sw: 'Weka alama za maji — kwenye kivinjari.' },
  // ── Flatten ──
  'page.flatten.h1a': { en: 'Flatten', ar: 'تسطيح', ur: 'فلیٹ کریں', hi: 'फ़्लैटन करें', es: 'Aplanar', fr: 'Aplatir le', de: 'PDF', zh: '扁平化', ja: 'PDFを', ko: 'PDF', tr: 'PDF', ru: 'Сгладить', it: 'Appiattisci', nl: 'PDF', id: 'Ratakan', th: 'ปรับ', vi: 'Làm phẳng', bn: 'ফ্ল্যাটেন করুন', sw: 'Sawazisha' },
  'page.flatten.h1b': { en: 'PDF', ar: 'PDF', ur: 'PDF', hi: 'PDF', es: 'PDF', fr: 'PDF', de: 'glätten', zh: 'PDF', ja: 'フラット化', ko: '플래튼', tr: 'düzleştir', ru: 'PDF', it: 'PDF', nl: 'plat maken', id: 'PDF', th: 'PDF ให้แบน', vi: 'PDF', bn: 'PDF', sw: 'PDF' },
  'page.flatten.sub': { en: 'Remove form fields, annotations, and layers — make your PDF static.', ar: 'أزل حقول النماذج والتعليقات والطبقات — اجعل PDF ثابتاً.', ur: 'فارم فیلڈز اور تبصرے ہٹائیں — PDF کو جامد بنائیں۔', hi: 'फ़ॉर्म फ़ील्ड और एनोटेशन हटाएं — PDF स्थिर बनाएं।', es: 'Elimina campos de formulario y anotaciones.', fr: 'Supprimez champs de formulaire et annotations.', de: 'Formularfelder und Anmerkungen entfernen.', zh: '移除表单字段、注释和图层 — 使PDF静态化。', ja: 'フォームフィールドと注釈を削除 — PDFを静的に。', ko: '양식 필드와 주석 제거 — PDF를 정적으로.', tr: 'Form alanlarını ve açıklamaları kaldırın.', ru: 'Удалите поля форм и аннотации.', it: 'Rimuovi campi modulo e annotazioni.', nl: 'Verwijder formuliervelden en annotaties.', id: 'Hapus kolom formulir dan anotasi.', th: 'ลบฟิลด์ฟอร์มและคำอธิบาย', vi: 'Xóa trường biểu mẫu và chú thích.', bn: 'ফর্ম ফিল্ড এবং টীকা সরান।', sw: 'Ondoa sehemu za fomu na maelezo.' },
  // ── Grayscale ──
  'page.grayscale.h1a': { en: 'Convert to', ar: 'تحويل إلى', ur: 'تبدیل کریں', hi: 'ग्रेस्केल में', es: 'Convertir a', fr: 'Convertir en', de: 'In Graustufen', zh: '转换为', ja: 'グレースケールに', ko: '그레이스케일로', tr: 'Gri tonlamaya', ru: 'Конвертировать в', it: 'Converti in', nl: 'Converteren naar', id: 'Konversi ke', th: 'แปลงเป็น', vi: 'Chuyển sang', bn: 'গ্রেস্কেলে রূপান্তর', sw: 'Badilisha kuwa' },
  'page.grayscale.h1b': { en: 'Grayscale', ar: 'تدرج رمادي', ur: 'گرے اسکیل', hi: 'बदलें', es: 'escala de grises', fr: 'niveaux de gris', de: 'umwandeln', zh: '灰度', ja: '変換', ko: '변환', tr: 'dönüştür', ru: 'оттенки серого', it: 'scala di grigi', nl: 'grijstinten', id: 'grayscale', th: 'โทนสีเทา', vi: 'xám', bn: 'করুন', sw: 'kijivu' },
  'page.grayscale.sub': { en: 'Remove colors from your PDF to reduce file size — processed entirely in your browser.', ar: 'أزل الألوان من PDF لتقليل الحجم — في متصفحك.', ur: 'فائل سائز کم کرنے کے لیے رنگ ہٹائیں — آپ کے براؤزر میں۔', hi: 'फ़ाइल साइज़ कम करने के लिए रंग हटाएं — ब्राउज़र में।', es: 'Elimina colores para reducir el tamaño — en tu navegador.', fr: 'Supprimez les couleurs pour réduire la taille — dans votre navigateur.', de: 'Farben entfernen, um die Dateigröße zu reduzieren — in Ihrem Browser.', zh: '去除PDF颜色以减小文件大小 — 在浏览器中完成。', ja: 'ファイルサイズ削減のため色を除去 — ブラウザ内で。', ko: '파일 크기 줄이기 위해 색상 제거 — 브라우저에서.', tr: 'Dosya boyutunu küçültmek için renkleri kaldırın — tarayıcınızda.', ru: 'Удалите цвета для уменьшения размера — в браузере.', it: 'Rimuovi i colori per ridurre le dimensioni — nel tuo browser.', nl: 'Kleuren verwijderen om bestandsgrootte te verkleinen — in je browser.', id: 'Hapus warna untuk mengurangi ukuran — di browser.', th: 'ลบสีเพื่อลดขนาดไฟล์ — ในเบราว์เซอร์', vi: 'Xóa màu để giảm kích thước — trong trình duyệt.', bn: 'ফাইলের আকার কমাতে রং সরান — ব্রাউজারে।', sw: 'Ondoa rangi kupunguza ukubwa — kwenye kivinjari.' },
  // ── Simple h1 pages (no h1a/h1b split) ──
  'page.signature.h1': { en: 'Add Signature to PDF', ar: 'إضافة توقيع إلى PDF', ur: 'PDF میں دستخط شامل کریں', hi: 'PDF में हस्ताक्षर जोड़ें', es: 'Añadir firma al PDF', fr: 'Ajouter une signature au PDF', de: 'Unterschrift zu PDF hinzufügen', zh: '给PDF添加签名', ja: 'PDFに署名を追加', ko: 'PDF에 서명 추가', tr: 'PDF\'ye imza ekle', ru: 'Добавить подпись в PDF', it: 'Aggiungi firma al PDF', nl: 'Handtekening aan PDF toevoegen', id: 'Tambahkan tanda tangan ke PDF', th: 'เพิ่มลายเซ็นใน PDF', vi: 'Thêm chữ ký vào PDF', bn: 'PDF এ স্বাক্ষর যোগ করুন', sw: 'Ongeza sahihi kwenye PDF' },
  'page.signature.sub': { en: 'Type your signature and place it on every page of your PDF.', ar: 'اكتب توقيعك وضعه على كل صفحة.', ur: 'اپنا دستخط لکھیں اور ہر صفحے پر رکھیں۔', hi: 'अपना हस्ताक्षर टाइप करें और हर पेज पर रखें।', es: 'Escribe tu firma y colócala en cada página.', fr: 'Tapez votre signature et placez-la sur chaque page.', de: 'Unterschrift eingeben und auf jede Seite platzieren.', zh: '输入签名并放置在每一页上。', ja: '署名を入力して各ページに配置。', ko: '서명을 입력하고 모든 페이지에 배치.', tr: 'İmzanızı yazın ve her sayfaya yerleştirin.', ru: 'Введите подпись и разместите на каждой странице.', it: 'Digita la tua firma e posizionala su ogni pagina.', nl: 'Typ je handtekening en plaats deze op elke pagina.', id: 'Ketik tanda tangan dan tempatkan di setiap halaman.', th: 'พิมพ์ลายเซ็นและวางบนทุกหน้า', vi: 'Nhập chữ ký và đặt lên mỗi trang.', bn: 'স্বাক্ষর টাইপ করুন এবং প্রতিটি পৃষ্ঠায় রাখুন।', sw: 'Andika sahihi yako na uiweke kwenye kila ukurasa.' },
  'page.metadata.h1': { en: 'Edit PDF Metadata', ar: 'تعديل بيانات PDF الوصفية', ur: 'PDF میٹا ڈیٹا میں ترمیم کریں', hi: 'PDF मेटाडेटा संपादित करें', es: 'Editar metadatos PDF', fr: 'Modifier les métadonnées PDF', de: 'PDF-Metadaten bearbeiten', zh: '编辑PDF元数据', ja: 'PDFメタデータの編集', ko: 'PDF 메타데이터 편집', tr: 'PDF meta verilerini düzenle', ru: 'Редактировать метаданные PDF', it: 'Modifica metadati PDF', nl: 'PDF-metadata bewerken', id: 'Edit metadata PDF', th: 'แก้ไข metadata PDF', vi: 'Chỉnh sửa metadata PDF', bn: 'PDF মেটাডেটা সম্পাদনা করুন', sw: 'Hariri metadata ya PDF' },
  'page.metadata.sub': { en: 'View and modify title, author, subject, keywords and more.', ar: 'عرض وتعديل العنوان والمؤلف والموضوع والكلمات المفتاحية.', ur: 'عنوان، مصنف، موضوع اور کلیدی الفاظ دیکھیں اور تبدیل کریں۔', hi: 'शीर्षक, लेखक, विषय, कीवर्ड देखें और बदलें।', es: 'Ver y modificar título, autor, tema y palabras clave.', fr: 'Affichez et modifiez le titre, l\'auteur, le sujet.', de: 'Titel, Autor, Betreff und Schlüsselwörter bearbeiten.', zh: '查看和修改标题、作者、主题、关键词等。', ja: 'タイトル、著者、件名、キーワードを表示・編集。', ko: '제목, 저자, 주제, 키워드 보기 및 수정.', tr: 'Başlık, yazar, konu ve anahtar kelimeleri düzenleyin.', ru: 'Просмотр и редактирование заголовка, автора и ключевых слов.', it: 'Visualizza e modifica titolo, autore, soggetto e parole chiave.', nl: 'Bekijk en bewerk titel, auteur, onderwerp en trefwoorden.', id: 'Lihat dan ubah judul, penulis, subjek dan kata kunci.', th: 'ดูและแก้ไขชื่อ ผู้แต่ง หัวเรื่อง คำสำคัญ', vi: 'Xem và sửa tiêu đề, tác giả, chủ đề, từ khóa.', bn: 'শিরোনাম, লেখক, বিষয়, কীওয়ার্ড দেখুন ও সম্পাদনা করুন।', sw: 'Tazama na ubadilishe kichwa, mwandishi, mada na maneno muhimu.' },
  'page.mergeImages.h1': { en: 'Merge Images to PDF', ar: 'دمج الصور في PDF', ur: 'تصاویر کو PDF میں ملائیں', hi: 'इमेज को PDF में मर्ज करें', es: 'Combinar imágenes en PDF', fr: 'Fusionner images en PDF', de: 'Bilder zu PDF zusammenführen', zh: '合并图片为PDF', ja: '画像をPDFに結合', ko: '이미지를 PDF로 병합', tr: 'Resimleri PDF\'ye birleştir', ru: 'Объединить изображения в PDF', it: 'Unisci immagini in PDF', nl: 'Afbeeldingen samenvoegen tot PDF', id: 'Gabung gambar ke PDF', th: 'รวมรูปภาพเป็น PDF', vi: 'Gộp ảnh thành PDF', bn: 'ছবি PDF এ মার্জ করুন', sw: 'Unganisha picha kuwa PDF' },
  'page.mergeImages.sub': { en: 'Combine multiple images (JPG, PNG, WEBP) into a single PDF. Drag to reorder pages.', ar: 'ادمج صوراً متعددة في ملف PDF واحد. اسحب لإعادة الترتيب.', ur: 'متعدد تصاویر کو ایک PDF میں ملائیں۔ ترتیب بدلنے کے لیے کھینچیں۔', hi: 'कई इमेज को एक PDF में मिलाएं। पुनर्व्यवस्थित करने के लिए खींचें।', es: 'Combina múltiples imágenes en un solo PDF. Arrastra para reordenar.', fr: 'Combinez plusieurs images en un seul PDF. Glissez pour réorganiser.', de: 'Mehrere Bilder zu einem PDF kombinieren. Ziehen zum Neuordnen.', zh: '将多张图片合并为一个PDF。拖动排序。', ja: '複数の画像を1つのPDFに。ドラッグで並べ替え。', ko: '여러 이미지를 하나의 PDF로. 드래그로 재정렬.', tr: 'Birden fazla resmi tek PDF\'de birleştirin. Sürükle bırak ile sıralayın.', ru: 'Объедините несколько изображений в один PDF. Перетаскивайте для сортировки.', it: 'Combina più immagini in un unico PDF. Trascina per riordinare.', nl: 'Combineer meerdere afbeeldingen tot één PDF. Sleep om te herschikken.', id: 'Gabungkan beberapa gambar menjadi satu PDF. Seret untuk mengatur ulang.', th: 'รวมรูปภาพหลายรูปเป็น PDF เดียว ลากเพื่อจัดเรียง', vi: 'Gộp nhiều ảnh thành một PDF. Kéo để sắp xếp.', bn: 'একাধিক ছবি একটি PDF তে মার্জ করুন। টেনে সাজান।', sw: 'Unganisha picha nyingi kuwa PDF moja. Buruta kupanga upya.' },
  // ── Batch ──
  'page.batch.h1a': { en: 'Batch', ar: 'معالجة دفعية', ur: 'بیچ', hi: 'बैच', es: 'Procesamiento', fr: 'Traitement par', de: 'Stapel', zh: '批量', ja: 'バッチ', ko: '일괄', tr: 'Toplu', ru: 'Пакетная', it: 'Elaborazione', nl: 'Batch', id: 'Pemrosesan', th: 'ประมวลผล', vi: 'Xử lý', bn: 'ব্যাচ', sw: 'Uchakataji' },
  'page.batch.h1b': { en: 'Processing', ar: '', ur: 'پروسیسنگ', hi: 'प्रोसेसिंग', es: 'por lotes', fr: 'lots', de: 'verarbeitung', zh: '处理', ja: '処理', ko: '처리', tr: 'işleme', ru: 'обработка', it: 'in batch', nl: 'verwerking', id: 'batch', th: 'เป็นชุด', vi: 'hàng loạt', bn: 'প্রসেসিং', sw: 'wa kundi' },
  'page.batch.sub': { en: 'Process multiple PDF files simultaneously with progress tracking.', ar: 'عالج عدة ملفات PDF في وقت واحد مع تتبع التقدم.', ur: 'متعدد PDF فائلیں بیک وقت پروسیس کریں۔', hi: 'एक साथ कई PDF फ़ाइलें प्रोसेस करें।', es: 'Procesa múltiples PDFs simultáneamente con seguimiento.', fr: 'Traitez plusieurs PDF simultanément avec suivi.', de: 'Mehrere PDFs gleichzeitig mit Fortschrittsanzeige verarbeiten.', zh: '同时处理多个PDF文件并跟踪进度。', ja: '複数のPDFを同時処理 — 進行状況付き。', ko: '여러 PDF를 동시에 처리 — 진행 상황 추적.', tr: 'Birden fazla PDF\'yi ilerleme takibi ile işleyin.', ru: 'Обрабатывайте несколько PDF одновременно с отслеживанием.', it: 'Elabora più PDF contemporaneamente con monitoraggio.', nl: 'Verwerk meerdere PDF\'s tegelijk met voortgang.', id: 'Proses beberapa PDF sekaligus dengan pelacakan progres.', th: 'ประมวลผลหลายไฟล์พร้อมติดตามความคืบหน้า', vi: 'Xử lý nhiều PDF cùng lúc với theo dõi tiến trình.', bn: 'একসাথে একাধিক PDF প্রসেস করুন।', sw: 'Chakata PDF nyingi kwa wakati mmoja.' },
  // ── Remaining tools ──
  'page.bgRemover.h1a': { en: 'Remove', ar: 'إزالة', ur: 'ہٹائیں', hi: 'हटाएं', es: 'Eliminar', fr: 'Supprimer les', de: 'Hintergründe', zh: '去除', ja: '背景を', ko: '배경', tr: 'Arka planları', ru: 'Удалить', it: 'Rimuovi', nl: 'Achtergronden', id: 'Hapus', th: 'ลบ', vi: 'Xóa', bn: 'সরান', sw: 'Ondoa' },
  'page.bgRemover.h1b': { en: 'backgrounds', ar: 'الخلفيات', ur: 'پس منظر', hi: 'बैकग्राउंड', es: 'fondos', fr: 'arrière-plans', de: 'entfernen', zh: '背景', ja: '削除', ko: '제거', tr: 'kaldır', ru: 'фон', it: 'sfondi', nl: 'verwijderen', id: 'latar belakang', th: 'พื้นหลัง', vi: 'nền', bn: 'ব্যাকগ্রাউন্ড', sw: 'mandhari' },
  'page.bgRemover.sub': { en: 'AI-powered background removal — 100% in your browser, no uploads.', ar: 'إزالة الخلفية بالذكاء الاصطناعي — 100% في متصفحك.', ur: 'AI سے پس منظر ہٹائیں — 100% آپ کے براؤزر میں۔', hi: 'AI से बैकग्राउंड हटाएं — 100% ब्राउज़र में।', es: 'Eliminación de fondo con IA — 100% en tu navegador.', fr: 'Suppression de fond par IA — 100% dans votre navigateur.', de: 'KI-gestützte Hintergrundentfernung — 100% in Ihrem Browser.', zh: 'AI驱动的背景去除 — 100%在浏览器中完成。', ja: 'AI背景除去 — 100%ブラウザ内で。', ko: 'AI 배경 제거 — 100% 브라우저에서.', tr: 'AI ile arka plan kaldırma — 100% tarayıcınızda.', ru: 'Удаление фона с помощью ИИ — 100% в браузере.', it: 'Rimozione sfondo con IA — 100% nel tuo browser.', nl: 'AI-achtergrondverwijdering — 100% in je browser.', id: 'Penghapusan latar belakang AI — 100% di browser.', th: 'ลบพื้นหลังด้วย AI — 100% ในเบราว์เซอร์', vi: 'Xóa nền bằng AI — 100% trong trình duyệt.', bn: 'AI ব্যাকগ্রাউন্ড সরানো — 100% ব্রাউজারে।', sw: 'Kuondoa mandhari kwa AI — 100% kwenye kivinjari.' },
  'page.ocrPdf.h1a': { en: 'OCR — Extract Text from', ar: 'OCR — استخراج النص من', ur: 'OCR — متن نکالیں', hi: 'OCR — टेक्स्ट निकालें', es: 'OCR — Extraer texto de', fr: 'OCR — Extraire le texte de', de: 'OCR — Text extrahieren aus', zh: 'OCR — 从扫描PDF中提取文字', ja: 'OCR — スキャンPDFからテキスト抽出', ko: 'OCR — 스캔 PDF에서 텍스트 추출', tr: 'OCR — Taranan PDF\'den metin çıkar', ru: 'OCR — Извлечь текст из', it: 'OCR — Estrai testo da', nl: 'OCR — Tekst extraheren uit', id: 'OCR — Ekstrak teks dari', th: 'OCR — ดึงข้อความจาก', vi: 'OCR — Trích xuất văn bản từ', bn: 'OCR — টেক্সট বের করুন', sw: 'OCR — Toa maandishi kutoka' },
  'page.ocrPdf.h1b': { en: 'Scanned PDFs', ar: 'PDF الممسوحة', ur: 'اسکین شدہ PDF', hi: 'स्कैन किए गए PDF', es: 'PDFs escaneados', fr: 'PDF numérisés', de: 'gescannten PDFs', zh: '', ja: '', ko: '', tr: '', ru: 'сканированных PDF', it: 'PDF scansionati', nl: 'gescande PDF\'s', id: 'PDF yang dipindai', th: 'PDF ที่สแกน', vi: 'PDF đã quét', bn: 'স্ক্যান করা PDF', sw: 'PDF zilizoskaniwa' },
  'page.ocrPdf.sub': { en: 'Convert scanned documents and images into searchable, editable text.', ar: 'حوّل المستندات الممسوحة إلى نص قابل للبحث والتحرير.', ur: 'اسکین شدہ دستاویزات کو قابل تلاش متن میں تبدیل کریں۔', hi: 'स्कैन किए दस्तावेज़ों को खोज योग्य टेक्स्ट में बदलें।', es: 'Convierte documentos escaneados en texto editable.', fr: 'Convertissez des documents numérisés en texte éditable.', de: 'Gescannte Dokumente in durchsuchbaren Text umwandeln.', zh: '将扫描文档转换为可搜索、可编辑的文字。', ja: 'スキャン文書を検索可能なテキストに変換。', ko: '스캔 문서를 검색 가능한 텍스트로 변환.', tr: 'Taranan belgeleri aranabilir metne dönüştürün.', ru: 'Конвертируйте сканы в редактируемый текст.', it: 'Converti documenti scansionati in testo modificabile.', nl: 'Converteer gescande documenten naar doorzoekbare tekst.', id: 'Konversi dokumen yang dipindai menjadi teks yang dapat dicari.', th: 'แปลงเอกสารที่สแกนเป็นข้อความที่ค้นหาได้', vi: 'Chuyển đổi tài liệu quét thành văn bản có thể tìm kiếm.', bn: 'স্ক্যান করা ডকুমেন্ট সার্চযোগ্য টেক্সটে রূপান্তর করুন।', sw: 'Badilisha hati zilizoskaniwa kuwa maandishi yanayoweza kutafutwa.' },
  'page.pdfToImages.h1a': { en: 'PDF to', ar: 'PDF إلى', ur: 'PDF سے', hi: 'PDF से', es: 'PDF a', fr: 'PDF en', de: 'PDF zu', zh: 'PDF转', ja: 'PDFを', ko: 'PDF를', tr: 'PDF\'den', ru: 'PDF в', it: 'PDF in', nl: 'PDF naar', id: 'PDF ke', th: 'PDF เป็น', vi: 'PDF sang', bn: 'PDF থেকে', sw: 'PDF hadi' },
  'page.pdfToImages.h1b': { en: 'Images', ar: 'صور', ur: 'تصاویر', hi: 'इमेज', es: 'Imágenes', fr: 'Images', de: 'Bilder', zh: '图片', ja: '画像に変換', ko: '이미지로', tr: 'Resimlere', ru: 'Изображения', it: 'Immagini', nl: 'Afbeeldingen', id: 'Gambar', th: 'รูปภาพ', vi: 'Ảnh', bn: 'ছবি', sw: 'Picha' },
  'page.pdfToImages.sub': { en: 'Convert each page to high-quality PNG or JPG — entirely in your browser.', ar: 'حوّل كل صفحة إلى PNG أو JPG عالي الجودة — في متصفحك.', ur: 'ہر صفحے کو اعلیٰ کوالٹی تصویر میں تبدیل کریں — آپ کے براؤزر میں۔', hi: 'हर पेज को उच्च-गुणवत्ता PNG या JPG में बदलें — ब्राउज़र में।', es: 'Convierte cada página a PNG o JPG de alta calidad.', fr: 'Convertissez chaque page en PNG ou JPG haute qualité.', de: 'Jede Seite in hochwertiges PNG oder JPG konvertieren.', zh: '将每页转换为高质量PNG或JPG — 在浏览器中完成。', ja: '各ページを高品質PNG/JPGに変換 — ブラウザ内で。', ko: '각 페이지를 고화질 PNG/JPG로 변환 — 브라우저에서.', tr: 'Her sayfayı yüksek kaliteli PNG/JPG\'ye dönüştürün.', ru: 'Конвертируйте каждую страницу в PNG или JPG.', it: 'Converti ogni pagina in PNG o JPG ad alta qualità.', nl: 'Converteer elke pagina naar hoogwaardige PNG of JPG.', id: 'Konversi setiap halaman ke PNG atau JPG berkualitas tinggi.', th: 'แปลงทุกหน้าเป็น PNG หรือ JPG คุณภาพสูง', vi: 'Chuyển mỗi trang thành PNG hoặc JPG chất lượng cao.', bn: 'প্রতিটি পৃষ্ঠা উচ্চ-মানের PNG বা JPG তে রূপান্তর করুন।', sw: 'Badilisha kila ukurasa kuwa PNG au JPG bora.' },
  'page.pdfEditor.h1a': { en: 'PDF', ar: 'محرر', ur: 'PDF', hi: 'PDF', es: 'Editor de', fr: 'Éditeur de', de: 'PDF-', zh: 'PDF', ja: 'PDF', ko: 'PDF', tr: 'PDF', ru: 'Редактор', it: 'Editor', nl: 'PDF-', id: 'Editor', th: 'แก้ไข', vi: 'Chỉnh sửa', bn: 'PDF', sw: 'Mhariri' },
  'page.pdfEditor.h1b': { en: 'Editor', ar: 'PDF', ur: 'ایڈیٹر', hi: 'एडिटर', es: 'PDF', fr: 'PDF', de: 'Editor', zh: '编辑器', ja: 'エディター', ko: '편집기', tr: 'Düzenleyici', ru: 'PDF', it: 'PDF', nl: 'editor', id: 'PDF', th: 'PDF', vi: 'PDF', bn: 'এডিটর', sw: 'wa PDF' },
  'page.pdfEditor.sub': { en: 'Add text, highlights, drawings, shapes, and images to your PDFs.', ar: 'أضف نصوصاً وتمييزات ورسومات وأشكالاً وصوراً إلى PDF.', ur: 'PDF میں متن، نشانیاں، ڈرائنگ شامل کریں۔', hi: 'PDF में टेक्स्ट, हाइलाइट, ड्रॉइंग, शेप जोड़ें।', es: 'Añade texto, resaltados, dibujos y formas a tus PDFs.', fr: 'Ajoutez texte, surlignages, dessins et formes à vos PDF.', de: 'Text, Hervorhebungen, Zeichnungen und Formen hinzufügen.', zh: '为PDF添加文本、高亮、绘图、形状和图片。', ja: 'テキスト、ハイライト、描画、図形を追加。', ko: '텍스트, 하이라이트, 그림, 도형 추가.', tr: 'PDF\'lere metin, vurgular, çizimler ekleyin.', ru: 'Добавьте текст, выделения, рисунки в PDF.', it: 'Aggiungi testo, evidenziazioni, disegni ai PDF.', nl: 'Tekst, markeringen, tekeningen toevoegen aan PDF.', id: 'Tambahkan teks, sorotan, gambar ke PDF.', th: 'เพิ่มข้อความ ไฮไลท์ รูปวาด รูปทรง', vi: 'Thêm văn bản, đánh dấu, hình vẽ vào PDF.', bn: 'PDF তে টেক্সট, হাইলাইট, ড্রয়িং যোগ করুন।', sw: 'Ongeza maandishi, picha na michoro kwenye PDF.' },
  'page.redact.h1a': { en: 'Redact', ar: 'تنقيح', ur: 'ریڈیکٹ کریں', hi: 'रिडैक्ट करें', es: 'Redactar', fr: 'Caviarder le', de: 'PDF', zh: '涂黑', ja: 'PDFを', ko: 'PDF', tr: 'PDF', ru: 'Зачернить', it: 'Oscura', nl: 'PDF', id: 'Redaksi', th: 'ปกปิดข้อมูล', vi: 'Che giấu', bn: 'রিড্যাক্ট করুন', sw: 'Hariri' },
  'page.redact.h1b': { en: 'PDF', ar: 'PDF', ur: 'PDF', hi: 'PDF', es: 'PDF', fr: 'PDF', de: 'schwärzen', zh: 'PDF', ja: '墨消し', ko: '교정', tr: 'redakte et', ru: 'PDF', it: 'PDF', nl: 'redigeren', id: 'PDF', th: 'PDF', vi: 'PDF', bn: 'PDF', sw: 'PDF' },
  'page.redact.sub': { en: 'Black out sensitive information — draw rectangles on any page.', ar: 'اطمس المعلومات الحساسة — ارسم مستطيلات على أي صفحة.', ur: 'حساس معلومات چھپائیں — کسی بھی صفحے پر مستطیل بنائیں۔', hi: 'संवेदनशील जानकारी छुपाएं — किसी भी पेज पर आयत बनाएं।', es: 'Oculta información sensible — dibuja rectángulos.', fr: 'Masquez les informations sensibles — dessinez des rectangles.', de: 'Sensible Informationen schwärzen — Rechtecke zeichnen.', zh: '涂黑敏感信息 — 在任意页面绘制矩形。', ja: '機密情報を黒塗り — 任意のページに矩形を描画。', ko: '민감한 정보 가리기 — 페이지에 사각형 그리기.', tr: 'Hassas bilgileri karartın — herhangi bir sayfaya dikdörtgen çizin.', ru: 'Зачерните конфиденциальную информацию.', it: 'Oscura informazioni sensibili — disegna rettangoli.', nl: 'Gevoelige informatie zwartmaken — rechthoeken tekenen.', id: 'Sembunyikan informasi sensitif — gambar persegi panjang.', th: 'ปกปิดข้อมูลที่สำคัญ — วาดสี่เหลี่ยมบนหน้าใดก็ได้', vi: 'Che giấu thông tin nhạy cảm — vẽ hình chữ nhật.', bn: 'সংবেদনশীল তথ্য ঢাকুন — আয়তক্ষেত্র আঁকুন।', sw: 'Ficha taarifa nyeti — chora mstatili.' },
  'page.unlock.h1a': { en: 'Unlock', ar: 'فتح', ur: 'انلاک کریں', hi: 'अनलॉक करें', es: 'Desbloquear', fr: 'Déverrouiller le', de: 'PDF', zh: '解锁', ja: 'PDFの', ko: 'PDF', tr: 'PDF', ru: 'Разблокировать', it: 'Sblocca', nl: 'PDF', id: 'Buka kunci', th: 'ปลดล็อค', vi: 'Mở khóa', bn: 'আনলক করুন', sw: 'Fungua' },
  'page.unlock.h1b': { en: 'PDF', ar: 'PDF', ur: 'PDF', hi: 'PDF', es: 'PDF', fr: 'PDF', de: 'entsperren', zh: 'PDF', ja: 'ロック解除', ko: '잠금 해제', tr: 'kilidini aç', ru: 'PDF', it: 'PDF', nl: 'ontgrendelen', id: 'PDF', th: 'PDF', vi: 'PDF', bn: 'PDF', sw: 'PDF' },
  'page.unlock.sub': { en: 'Remove print, copy, and edit restrictions from your PDF files.', ar: 'أزل قيود الطباعة والنسخ والتحرير من ملفات PDF.', ur: 'PDF فائلوں سے پرنٹ، کاپی اور ایڈٹ پابندیاں ہٹائیں۔', hi: 'PDF फ़ाइलों से प्रिंट, कॉपी और एडिट प्रतिबंध हटाएं।', es: 'Elimina restricciones de impresión, copia y edición.', fr: 'Supprimez les restrictions d\'impression, copie et édition.', de: 'Druck-, Kopier- und Bearbeitungsbeschränkungen entfernen.', zh: '移除PDF文件的打印、复制和编辑限制。', ja: '印刷・コピー・編集制限を解除。', ko: '인쇄, 복사, 편집 제한 제거.', tr: 'Yazdırma, kopyalama ve düzenleme kısıtlamalarını kaldırın.', ru: 'Удалите ограничения печати, копирования и редактирования.', it: 'Rimuovi restrizioni di stampa, copia e modifica.', nl: 'Verwijder print-, kopieer- en bewerkingsbeperkingen.', id: 'Hapus batasan cetak, salin dan edit dari PDF.', th: 'ลบข้อจำกัดการพิมพ์ คัดลอก และแก้ไข', vi: 'Xóa hạn chế in, sao chép và chỉnh sửa.', bn: 'প্রিন্ট, কপি এবং এডিট সীমাবদ্ধতা সরান।', sw: 'Ondoa vizuizi vya kuchapisha, kunakili na kuhariri.' },
  'page.watermarkRemover.h1a': { en: 'Remove', ar: 'إزالة', ur: 'ہٹائیں', hi: 'हटाएं', es: 'Eliminar', fr: 'Supprimer les', de: 'Wasserzeichen', zh: '去除', ja: '透かしを', ko: '워터마크', tr: 'Filigranları', ru: 'Удалить', it: 'Rimuovi', nl: 'Watermerken', id: 'Hapus', th: 'ลบ', vi: 'Xóa', bn: 'সরান', sw: 'Ondoa' },
  'page.watermarkRemover.h1b': { en: 'watermarks', ar: 'العلامات المائية', ur: 'واٹر مارک', hi: 'वॉटरमार्क', es: 'marcas de agua', fr: 'filigranes', de: 'entfernen', zh: '水印', ja: '削除', ko: '제거', tr: 'kaldır', ru: 'водяные знаки', it: 'filigrane', nl: 'verwijderen', id: 'watermark', th: 'ลายน้ำ', vi: 'watermark', bn: 'ওয়াটারমার্ক', sw: 'alama za maji' },
  'page.watermarkRemover.sub': { en: 'Strip watermarks from PDF files — processed locally in your browser.', ar: 'أزل العلامات المائية من ملفات PDF — في متصفحك.', ur: 'PDF فائلوں سے واٹر مارک ہٹائیں — آپ کے براؤزر میں۔', hi: 'PDF फ़ाइलों से वॉटरमार्क हटाएं — ब्राउज़र में।', es: 'Elimina marcas de agua de archivos PDF — en tu navegador.', fr: 'Supprimez les filigranes des PDF — dans votre navigateur.', de: 'Wasserzeichen aus PDF-Dateien entfernen — in Ihrem Browser.', zh: '从PDF文件中去除水印 — 在浏览器中完成。', ja: 'PDFファイルから透かしを削除 — ブラウザ内で。', ko: 'PDF 파일에서 워터마크 제거 — 브라우저에서.', tr: 'PDF dosyalarından filigranları kaldırın — tarayıcınızda.', ru: 'Удалите водяные знаки из PDF — в браузере.', it: 'Rimuovi filigrane dai PDF — nel tuo browser.', nl: 'Verwijder watermerken uit PDF\'s — in je browser.', id: 'Hapus watermark dari file PDF — di browser.', th: 'ลบลายน้ำจากไฟล์ PDF — ในเบราว์เซอร์', vi: 'Xóa watermark khỏi PDF — trong trình duyệt.', bn: 'PDF ফাইল থেকে ওয়াটারমার্ক সরান — ব্রাউজারে।', sw: 'Ondoa alama za maji kutoka PDF — kwenye kivinjari.' },
  'page.svgToImage.h1': { en: 'SVG to Image Converter', ar: 'محوّل SVG إلى صورة', ur: 'SVG سے تصویر کنورٹر', hi: 'SVG से इमेज कन्वर्टर', es: 'Convertidor SVG a imagen', fr: 'Convertisseur SVG en image', de: 'SVG zu Bild Konverter', zh: 'SVG转图片转换器', ja: 'SVGから画像コンバーター', ko: 'SVG를 이미지로 변환기', tr: 'SVG\'den resme dönüştürücü', ru: 'Конвертер SVG в изображение', it: 'Convertitore SVG in immagine', nl: 'SVG naar afbeelding converter', id: 'Konverter SVG ke gambar', th: 'ตัวแปลง SVG เป็นรูปภาพ', vi: 'Bộ chuyển đổi SVG sang ảnh', bn: 'SVG থেকে ইমেজ কনভার্টার', sw: 'Kibadilishaji SVG hadi picha' },
  'page.svgToImage.sub': { en: 'Convert any SVG file to PNG, JPG, WEBP, or BMP — pick your format and scale. 100% browser-based, your files never leave your device.', ar: 'حوّل أي ملف SVG إلى PNG أو JPG أو WEBP أو BMP — اختر الصيغة والحجم. 100% في المتصفح.', ur: 'کسی بھی SVG کو PNG، JPG، WEBP میں تبدیل کریں — 100% براؤزر میں۔', hi: 'किसी भी SVG को PNG, JPG, WEBP में बदलें — 100% ब्राउज़र में।', es: 'Convierte SVG a PNG, JPG, WEBP o BMP — 100% en el navegador.', fr: 'Convertissez SVG en PNG, JPG, WEBP — 100% dans le navigateur.', de: 'SVG in PNG, JPG, WEBP konvertieren — 100% im Browser.', zh: '将SVG转换为PNG、JPG、WEBP — 100%在浏览器中。', ja: 'SVGをPNG、JPG、WEBPに変換 — 100%ブラウザ内で。', ko: 'SVG를 PNG, JPG, WEBP로 변환 — 100% 브라우저에서.', tr: 'SVG\'yi PNG, JPG, WEBP\'ye dönüştürün — 100% tarayıcıda.', ru: 'Конвертируйте SVG в PNG, JPG, WEBP — 100% в браузере.', it: 'Converti SVG in PNG, JPG, WEBP — 100% nel browser.', nl: 'Converteer SVG naar PNG, JPG, WEBP — 100% in de browser.', id: 'Konversi SVG ke PNG, JPG, WEBP — 100% di browser.', th: 'แปลง SVG เป็น PNG, JPG, WEBP — 100% ในเบราว์เซอร์', vi: 'Chuyển đổi SVG sang PNG, JPG, WEBP — 100% trong trình duyệt.', bn: 'SVG থেকে PNG, JPG, WEBP তে রূপান্তর করুন — 100% ব্রাউজারে।', sw: 'Badilisha SVG kuwa PNG, JPG, WEBP — 100% kwenye kivinjari.' },
};

// Helper to get tool translation with fallback to English
export function tt(key: string, lang: string): string {
  const entry = toolTranslations[key];
  if (!entry) return key;
  return entry[lang as Lang] || entry.en || key;
}
